    <!-- Vendor Scripts -->
    <script src="{{ asset('/assets/plugins/jquery/jquery.min.js') }}"></script>
    <script src="{{ asset('/assets/plugins/jquery/jquery-migrate.min.js') }}"></script>
    <script src="{{ asset('/assets/plugins/bootstrap-4/js/bootstrap.bundle.min.js') }}"></script>
    <!-- Plugin's Scripts -->
    <script src="{{ asset('/assets/plugins/fancybox/jquery.fancybox.min.js') }}"></script>
    <script src="{{ asset('/assets/plugins/nice-select/jquery.nice-select.min.js') }}"></script>
    <script src="{{ asset('/assets/plugins/aos/aos.min.js') }}"></script>
    <script src="{{ asset('/assets/plugins/slick/slick.min.js') }}"></script>
    <!-- Activation Script -->
    <script src="{{ asset('/assets/js/custom.js') }}"></script>